[package]
name = "compact-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
compact-core = { path = "../crates/compact-core" }
libfuzzer-sys = "0.4"

[[bin]]
name = "frame_decode"
path = "fuzz_targets/frame_decode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "cmp3_decode"
path = "fuzz_targets/cmp3_decode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "cmp4_decode"
path = "fuzz_targets/cmp4_decode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "search_decode"
path = "fuzz_targets/search_decode.rs"
test = false
doc = false
bench = false
